; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

; Generated by VC++ for Common Language Runtime
.file "E:\PrivateWorkspace\PortfolioServer\Common\lz4\x64\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
