INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (1, 'MeleeMinDamage', '근접 최소 공격력');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (2, 'MeleeMaxDamage', '근접 최대 공격력');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (3, 'MeleeDamage', '근접 공격력');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (4, 'MeleeDefence', '물리 방어력');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (5, 'CriticalRate', '치명타 확률');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (6, 'CriticalDamageRate', '치명타 데미지 배율');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (7, 'AttackSpeed', '공격 속도');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (8, 'MovementSpeed', '이동 속도');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (9, 'HitRate', '명중률');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (10, 'DodgeRate', '회피율');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (11, 'BlockRate', '막기 확률');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (12, 'CurrentHP', '현재 체력');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (13, 'CurrentMP', '현재 내공');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (14, 'MaxHP', '최대 체력');
INSERT INTO [dbo].[AbilityComponents] (Seq, AbilityName, Comment) VALUES (15, 'MaxMP', '최대 내공');