// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CSEnterGameReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CSEnterGameReq GetRootAsCSEnterGameReq(ByteBuffer _bb) { return GetRootAsCSEnterGameReq(_bb, new CSEnterGameReq()); }
  public static CSEnterGameReq GetRootAsCSEnterGameReq(ByteBuffer _bb, CSEnterGameReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CSEnterGameReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccountID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountIDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetAccountIDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetAccountIDArray() { return __p.__vector_as_array<byte>(4); }
  public string AccountPW { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountPWBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetAccountPWBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetAccountPWArray() { return __p.__vector_as_array<byte>(6); }
  public int HostID { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public EPacketProtocol Messageid { get { int o = __p.__offset(10); return o != 0 ? (EPacketProtocol)__p.bb.GetInt(o + __p.bb_pos) : EPacketProtocol.CS_EnterGameReq; } }

  public static Offset<CSEnterGameReq> CreateCSEnterGameReq(FlatBufferBuilder builder,
      StringOffset AccountIDOffset = default(StringOffset),
      StringOffset AccountPWOffset = default(StringOffset),
      int HostID = 0,
      EPacketProtocol messageid = EPacketProtocol.CS_EnterGameReq) {
    builder.StartTable(4);
    CSEnterGameReq.AddMessageid(builder, messageid);
    CSEnterGameReq.AddHostID(builder, HostID);
    CSEnterGameReq.AddAccountPW(builder, AccountPWOffset);
    CSEnterGameReq.AddAccountID(builder, AccountIDOffset);
    return CSEnterGameReq.EndCSEnterGameReq(builder);
  }

  public static void StartCSEnterGameReq(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddAccountID(FlatBufferBuilder builder, StringOffset AccountIDOffset) { builder.AddOffset(0, AccountIDOffset.Value, 0); }
  public static void AddAccountPW(FlatBufferBuilder builder, StringOffset AccountPWOffset) { builder.AddOffset(1, AccountPWOffset.Value, 0); }
  public static void AddHostID(FlatBufferBuilder builder, int HostID) { builder.AddInt(2, HostID, 0); }
  public static void AddMessageid(FlatBufferBuilder builder, EPacketProtocol messageid) { builder.AddInt(3, (int)messageid, 50002); }
  public static Offset<CSEnterGameReq> EndCSEnterGameReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CSEnterGameReq>(o);
  }
  public CSEnterGameReqT UnPack() {
    var _o = new CSEnterGameReqT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CSEnterGameReqT _o) {
    _o.AccountID = this.AccountID;
    _o.AccountPW = this.AccountPW;
    _o.HostID = this.HostID;
    _o.Messageid = this.Messageid;
  }
  public static Offset<CSEnterGameReq> Pack(FlatBufferBuilder builder, CSEnterGameReqT _o) {
    if (_o == null) return default(Offset<CSEnterGameReq>);
    var _AccountID = _o.AccountID == null ? default(StringOffset) : builder.CreateString(_o.AccountID);
    var _AccountPW = _o.AccountPW == null ? default(StringOffset) : builder.CreateString(_o.AccountPW);
    return CreateCSEnterGameReq(
      builder,
      _AccountID,
      _AccountPW,
      _o.HostID,
      _o.Messageid);
  }
};

public class CSEnterGameReqT
{
  public string AccountID { get; set; }
  public string AccountPW { get; set; }
  public int HostID { get; set; }
  public EPacketProtocol Messageid { get; set; }

  public CSEnterGameReqT() {
    this.AccountID = null;
    this.AccountPW = null;
    this.HostID = 0;
    this.Messageid = EPacketProtocol.CS_EnterGameReq;
  }
}

