// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DUserBuff : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DUserBuff GetRootAsDUserBuff(ByteBuffer _bb) { return GetRootAsDUserBuff(_bb, new DUserBuff()); }
  public static DUserBuff GetRootAsDUserBuff(ByteBuffer _bb, DUserBuff obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DUserBuff __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int SkillModuleID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long RemainMS { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<DUserBuff> CreateDUserBuff(FlatBufferBuilder builder,
      int SkillModuleID = 0,
      long RemainMS = 0) {
    builder.StartTable(2);
    DUserBuff.AddRemainMS(builder, RemainMS);
    DUserBuff.AddSkillModuleID(builder, SkillModuleID);
    return DUserBuff.EndDUserBuff(builder);
  }

  public static void StartDUserBuff(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSkillModuleID(FlatBufferBuilder builder, int SkillModuleID) { builder.AddInt(0, SkillModuleID, 0); }
  public static void AddRemainMS(FlatBufferBuilder builder, long RemainMS) { builder.AddLong(1, RemainMS, 0); }
  public static Offset<DUserBuff> EndDUserBuff(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<DUserBuff>(o);
  }
  public DUserBuffT UnPack() {
    var _o = new DUserBuffT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(DUserBuffT _o) {
    _o.SkillModuleID = this.SkillModuleID;
    _o.RemainMS = this.RemainMS;
  }
  public static Offset<DUserBuff> Pack(FlatBufferBuilder builder, DUserBuffT _o) {
    if (_o == null) return default(Offset<DUserBuff>);
    return CreateDUserBuff(
      builder,
      _o.SkillModuleID,
      _o.RemainMS);
  }
};

public class DUserBuffT
{
  public int SkillModuleID { get; set; }
  public long RemainMS { get; set; }

  public DUserBuffT() {
    this.SkillModuleID = 0;
    this.RemainMS = 0;
  }
}

