// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum EPacketProtocol : int
{
  None = 0,
  Host_Connect = 1,
  Host_Close = 2,
  Host_ConnectFailed = 3,
  Host_Hello = 12,
  SC_IntegrationErrorNotification = 10000,
  //////////////////////////////////////////////////////////
  CL_AuthReq = 10001,
  LUDB_AuthReq = 10002,
  UDBL_AuthRes = 10003,
  LC_AuthRes = 10004,
  LC_AuthErrorRes = 10005,
  LS_KickDuplicateConnectUserReq = 10006,
  LUDB_ConnectServerIDClear = 10007,
  LP_AuthLoginReq = 10008,
  PL_AuthLoginRes = 10009,
  CS_AuthReq = 10101,
  CS_EnterGameReq = 10102,
  SC_EnterGameAck = 10103,
  PacketMax = 10104,
};

