// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum EPacketProtocol : int
{
  //////////////////////////////////////////////////////////
  None = 0,
  Host_Connect = 1,
  Host_Close = 2,
  Host_ConnectFailed = 3,
  Host_Hello = 12,
  SC_IntegrationErrorNotification = 10000,
  //////////////////////////////////////////////////////////
  CL_AuthReq = 10001,
  LUDB_AuthReq = 10002,
  UDBL_AuthRes = 10003,
  LC_AuthRes = 10004,
  LC_AuthErrorRes = 10005,
  LS_KickDuplicateConnectUserReq = 10006,
  LUDB_ConnectServerIDClear = 10007,
  LS_Connect = 10008,
  LP_AuthLoginReq = 10009,
  PL_AuthLoginRes = 10010,
  CL_ConnectGameServerReq = 10011,
  LC_ConnectGameServerRes = 10012,
  //////////////////////////////////////////////////////////
  SC_SyncBehaviorData = 21000,
  //////////////////////////////////////////////////////////
  CS_AuthReq = 50001,
  CS_EnterGameReq = 50002,
  SC_EnterGameAck = 50003,
  PacketMax = 50004,
};

