// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LCAuthErrorRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static LCAuthErrorRes GetRootAsLCAuthErrorRes(ByteBuffer _bb) { return GetRootAsLCAuthErrorRes(_bb, new LCAuthErrorRes()); }
  public static LCAuthErrorRes GetRootAsLCAuthErrorRes(ByteBuffer _bb, LCAuthErrorRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LCAuthErrorRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ErrorCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public EPacketProtocol Messageid { get { int o = __p.__offset(8); return o != 0 ? (EPacketProtocol)__p.bb.GetInt(o + __p.bb_pos) : EPacketProtocol.LC_AuthErrorRes; } }

  public static Offset<LCAuthErrorRes> CreateLCAuthErrorRes(FlatBufferBuilder builder,
      int ErrorCode = 0,
      int Value = 0,
      EPacketProtocol messageid = EPacketProtocol.LC_AuthErrorRes) {
    builder.StartTable(3);
    LCAuthErrorRes.AddMessageid(builder, messageid);
    LCAuthErrorRes.AddValue(builder, Value);
    LCAuthErrorRes.AddErrorCode(builder, ErrorCode);
    return LCAuthErrorRes.EndLCAuthErrorRes(builder);
  }

  public static void StartLCAuthErrorRes(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddErrorCode(FlatBufferBuilder builder, int ErrorCode) { builder.AddInt(0, ErrorCode, 0); }
  public static void AddValue(FlatBufferBuilder builder, int Value) { builder.AddInt(1, Value, 0); }
  public static void AddMessageid(FlatBufferBuilder builder, EPacketProtocol messageid) { builder.AddInt(2, (int)messageid, 10005); }
  public static Offset<LCAuthErrorRes> EndLCAuthErrorRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<LCAuthErrorRes>(o);
  }
  public LCAuthErrorResT UnPack() {
    var _o = new LCAuthErrorResT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LCAuthErrorResT _o) {
    _o.ErrorCode = this.ErrorCode;
    _o.Value = this.Value;
    _o.Messageid = this.Messageid;
  }
  public static Offset<LCAuthErrorRes> Pack(FlatBufferBuilder builder, LCAuthErrorResT _o) {
    if (_o == null) return default(Offset<LCAuthErrorRes>);
    return CreateLCAuthErrorRes(
      builder,
      _o.ErrorCode,
      _o.Value,
      _o.Messageid);
  }
};

public class LCAuthErrorResT
{
  public int ErrorCode { get; set; }
  public int Value { get; set; }
  public EPacketProtocol Messageid { get; set; }

  public LCAuthErrorResT() {
    this.ErrorCode = 0;
    this.Value = 0;
    this.Messageid = EPacketProtocol.LC_AuthErrorRes;
  }
}

