// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SCIntegrationErrorNotification : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SCIntegrationErrorNotification GetRootAsSCIntegrationErrorNotification(ByteBuffer _bb) { return GetRootAsSCIntegrationErrorNotification(_bb, new SCIntegrationErrorNotification()); }
  public static SCIntegrationErrorNotification GetRootAsSCIntegrationErrorNotification(ByteBuffer _bb, SCIntegrationErrorNotification obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SCIntegrationErrorNotification __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int SrcMsgID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Error { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public EPacketProtocol Messageid { get { int o = __p.__offset(8); return o != 0 ? (EPacketProtocol)__p.bb.GetInt(o + __p.bb_pos) : EPacketProtocol.SC_IntegrationErrorNotification; } }

  public static Offset<SCIntegrationErrorNotification> CreateSCIntegrationErrorNotification(FlatBufferBuilder builder,
      int SrcMsgID = 0,
      int Error = 0,
      EPacketProtocol messageid = EPacketProtocol.SC_IntegrationErrorNotification) {
    builder.StartTable(3);
    SCIntegrationErrorNotification.AddMessageid(builder, messageid);
    SCIntegrationErrorNotification.AddError(builder, Error);
    SCIntegrationErrorNotification.AddSrcMsgID(builder, SrcMsgID);
    return SCIntegrationErrorNotification.EndSCIntegrationErrorNotification(builder);
  }

  public static void StartSCIntegrationErrorNotification(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSrcMsgID(FlatBufferBuilder builder, int SrcMsgID) { builder.AddInt(0, SrcMsgID, 0); }
  public static void AddError(FlatBufferBuilder builder, int Error) { builder.AddInt(1, Error, 0); }
  public static void AddMessageid(FlatBufferBuilder builder, EPacketProtocol messageid) { builder.AddInt(2, (int)messageid, 10000); }
  public static Offset<SCIntegrationErrorNotification> EndSCIntegrationErrorNotification(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SCIntegrationErrorNotification>(o);
  }
  public SCIntegrationErrorNotificationT UnPack() {
    var _o = new SCIntegrationErrorNotificationT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SCIntegrationErrorNotificationT _o) {
    _o.SrcMsgID = this.SrcMsgID;
    _o.Error = this.Error;
    _o.Messageid = this.Messageid;
  }
  public static Offset<SCIntegrationErrorNotification> Pack(FlatBufferBuilder builder, SCIntegrationErrorNotificationT _o) {
    if (_o == null) return default(Offset<SCIntegrationErrorNotification>);
    return CreateSCIntegrationErrorNotification(
      builder,
      _o.SrcMsgID,
      _o.Error,
      _o.Messageid);
  }
};

public class SCIntegrationErrorNotificationT
{
  public int SrcMsgID { get; set; }
  public int Error { get; set; }
  public EPacketProtocol Messageid { get; set; }

  public SCIntegrationErrorNotificationT() {
    this.SrcMsgID = 0;
    this.Error = 0;
    this.Messageid = EPacketProtocol.SC_IntegrationErrorNotification;
  }
}

