// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Sync : byte
{
  NONE = 0,
  Add = 1,
};

public class SyncUnion {
  public Sync Type { get; set; }
  public object Value { get; set; }

  public SyncUnion() {
    this.Type = Sync.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public SCAddSyncDataT AsAdd() { return this.As<SCAddSyncDataT>(); }

  public static int Pack(FlatBuffers.FlatBufferBuilder builder, SyncUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case Sync.Add: return SCAddSyncData.Pack(builder, _o.AsAdd()).Value;
    }
  }
}

