#pragma once

enum class EServerConst : int
{
    None = 0,

    APPLE_JWT_ISS = 1101,
    APPLE_JWT_AUD = 1102,
    APPLE_JWT_AUD2 = 1103,

    APPLE_VIA_FIREBASE_JWT_ISS = 1201,
    APPLE_VIA_FIREBASE_JWT_AUD = 1202,

    //EOS::Type ±‚¡ÿ
    CLIENT_VERSION_IOS_MIN = 2101,
    CLIENT_VERSION_IOS_MAX = 2102,

    CLIENT_VERSION_ANDROID_MIN = 2111,
    CLIENT_VERSION_ANDROID_MAX = 2112,

    CLIENT_VERSION_WINDOWS_UNIVERSAL_MIN = 2121,
    CLIENT_VERSION_WINDOWS_UNIVERSAL_MAX = 2122,
};