// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum EErrorMsg : int
{
  EF_NONE = 0,
  EF_HOST_IP_IS_NOT_ALLOWED = 11,
  EF_DUPLICATE_CONNECTION_NET_ALLOWED = 12,
  EF_LOGIN_PF_ERROR = 101,
  EF_KICK = 10201,
  EF_KICK_MAINTENANCE = 10202,
  EF_KICK_DUPLICATE_LOGIN = 10211,
};

