// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
public enum EPacketProtocol : int
{
  None = 0,
  Host_Connect = 1,
  Host_Close = 2,
  Host_ConnectFailed = 3,
  Host_Hello = 12,
  CS_AuthReq = 13,
  SC_AuthRes = 14,
  PacketMax = 15,
};

