// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
public enum EPacketProtocol : int
{
  None = 0,
  Host_Connect = 1,
  Host_Close = 2,
  Host_ConnectFailed = 3,
  Host_Hello = 12,
  SC_IntegrationErrorNotification = 10000,
  CL_AuthReq = 10001,
  LC_AuthRes = 10002,
  CS_EnterGameReq = 10003,
  SC_EnterGameAck = 10004,
  PacketMax = 10005,
};

