// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SCAuthRes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SCAuthRes GetRootAsSCAuthRes(ByteBuffer _bb) { return GetRootAsSCAuthRes(_bb, new SCAuthRes()); }
  public static SCAuthRes GetRootAsSCAuthRes(ByteBuffer _bb, SCAuthRes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SCAuthRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Accountid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountidBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetAccountidBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetAccountidArray() { return __p.__vector_as_array<byte>(4); }
  public string Accountpw { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountpwBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetAccountpwBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetAccountpwArray() { return __p.__vector_as_array<byte>(6); }
  public EPacketProtocol Messageid { get { int o = __p.__offset(8); return o != 0 ? (EPacketProtocol)__p.bb.GetInt(o + __p.bb_pos) : EPacketProtocol.SC_AuthRes; } }

  public static Offset<SCAuthRes> CreateSCAuthRes(FlatBufferBuilder builder,
      StringOffset accountidOffset = default(StringOffset),
      StringOffset accountpwOffset = default(StringOffset),
      EPacketProtocol messageid = EPacketProtocol.SC_AuthRes) {
    builder.StartTable(3);
    SCAuthRes.AddMessageid(builder, messageid);
    SCAuthRes.AddAccountpw(builder, accountpwOffset);
    SCAuthRes.AddAccountid(builder, accountidOffset);
    return SCAuthRes.EndSCAuthRes(builder);
  }

  public static void StartSCAuthRes(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddAccountid(FlatBufferBuilder builder, StringOffset accountidOffset) { builder.AddOffset(0, accountidOffset.Value, 0); }
  public static void AddAccountpw(FlatBufferBuilder builder, StringOffset accountpwOffset) { builder.AddOffset(1, accountpwOffset.Value, 0); }
  public static void AddMessageid(FlatBufferBuilder builder, EPacketProtocol messageid) { builder.AddInt(2, (int)messageid, 10002); }
  public static Offset<SCAuthRes> EndSCAuthRes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SCAuthRes>(o);
  }
  public SCAuthResT UnPack() {
    var _o = new SCAuthResT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SCAuthResT _o) {
    _o.Accountid = this.Accountid;
    _o.Accountpw = this.Accountpw;
    _o.Messageid = this.Messageid;
  }
  public static Offset<SCAuthRes> Pack(FlatBufferBuilder builder, SCAuthResT _o) {
    if (_o == null) return default(Offset<SCAuthRes>);
    var _accountid = _o.Accountid == null ? default(StringOffset) : builder.CreateString(_o.Accountid);
    var _accountpw = _o.Accountpw == null ? default(StringOffset) : builder.CreateString(_o.Accountpw);
    return CreateSCAuthRes(
      builder,
      _accountid,
      _accountpw,
      _o.Messageid);
  }
};

public class SCAuthResT
{
  public string Accountid { get; set; }
  public string Accountpw { get; set; }
  public EPacketProtocol Messageid { get; set; }

  public SCAuthResT() {
    this.Accountid = null;
    this.Accountpw = null;
    this.Messageid = EPacketProtocol.SC_AuthRes;
  }
}

